webtalk_init -webtalk_dir C:/Users/4ever/Documents/GitHub/SOMvhdl/SOMvhdl.sim/sim_1/behav/xsim/xsim.dir/init_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 22 00:19:20 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2960000" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ed7aa81-4833-4855-994b-39e685809587" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f491735d04444612b87a86f0f04388df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "128690055 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "14.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "33068_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2209813510 -regid "" -xml C:/Users/4ever/Documents/GitHub/SOMvhdl/SOMvhdl.sim/sim_1/behav/xsim/xsim.dir/init_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/4ever/Documents/GitHub/SOMvhdl/SOMvhdl.sim/sim_1/behav/xsim/xsim.dir/init_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/4ever/Documents/GitHub/SOMvhdl/SOMvhdl.sim/sim_1/behav/xsim/xsim.dir/init_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
