# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_serial/fifo_serial.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_serial || ORIG_REF_NAME==fifo_serial} -quiet] -quiet
